### ISSUE TITLE
Service name auto trim and limit length causing not match with IAM policy when set specific resource arn

### ISSUE THREAD

**Issue by kwongkz** [FidelLimited/serverless-plugin-warmup#219] opened 2020-07-30 02:28 UTC
My example service name is Testing123-ABC-Admin-Application
stage is stg

Expected result of event rule name: **Testing123-ABC-Admin-Application-stg-Serverless-WarmUpPluginEventsRuleSc-1T7AV9Z0GRSYH**
Actual result of event rule name: **Testing123-ABC-Admin-Application-WarmUpPluginEventsRuleSc-1T7AV9Z0GRSYH**

Because My IAM Policy was set as specific resource arn: **arn:aws:events:ap-southeast-1:ACCOUNT_ID:rule/Testing123-ABC-Admin-Application-stg***

`An error occurred: WarmUpPluginEventsRuleSchedule1 - User: arn:aws:sts::ACCOUNT_ID:assumed-role/stg-Testing123-ABC-Admin-Application-Cloudformation-Role/AWSCloudFormation is not authorized to perform: events:PutRule on resource: arn:aws:events:ap-southeast-1:ACCOUNT_ID:rule/Testing123-ABC-Admin-Application-WarmUpPluginEventsRuleSc-1T7AV9Z0GRSYH (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: AccessDeniedException;`

Seems like serverless-plugin-warmup will auto trim and limit the event rule name.

**Comment by juanjoDiaz** [comment] 2020-07-30 11:34
This plugin doesn't trim nor limit the event rule name. I double-checked on the codebase and I couldn't find any manipulation of the name. Please correct me if I'm missing something.

Maybe the issue is with the serverless framework itself generating the name?
Maybe trimming it to comply with the AWS limits or something like that.
You can also give the even a custom name (see https://www.serverless.com/framework/docs/providers/aws/events/schedule#specify-name-and-description). Not sure if that helps.

**Comment by kwongkz** [comment] 2020-07-30 12:52
> This plugin doesn't trim nor limit the event rule name. I double-checked on the codebase and I couldn't find any manipulation of the name. Please correct me if I'm missing something.
> 
> Maybe the issue is with the serverless framework itself generating the name?
> Maybe trimming it to comply with the AWS limits or something like that.
> You can also give the even a custom name (see https://www.serverless.com/framework/docs/providers/aws/events/schedule#specify-name-and-description). Not sure if that helps.

Thanks @juanjoDiaz, but I did tried to put custom name follow like the link but warmup setting not support this variable

**Comment by juanjoDiaz** [comment] 2020-11-27 16:27
Hi @kwongkz sorry for the silence.
Did you ever get anywhere with this?

WarmUp just passes the events through to serverless so it should work just as in serverless.
What kind of error did you get?
I've seen that some versions of serverless don't enable the scheduled rule by default but you need to explicitly set the `enabled: true`, might that be your case?

**Comment by juanjoDiaz** [comment] 2020-11-29 13:57
I tested the following config using the latest serverless release.

```yaml
  warmup:
    enabled: true
    events:
      - schedule:
          name: my-warmup-schedule
          description: 'My scheduled rate event description'
          rate: rate(2 minutes)
```

and the rule was called `my-warmup-schedule` as expected.

Closing this. Feel free to reopen if there is anything else missing.

**Closed** 2020-11-29 13:57 UTC
