### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by zemacnica** [FidelLimited/serverless-plugin-warmup#212] opened 2020-04-08 11:11 UTC
Hi,

I have problem to deploy due to syntax error in plugin

lambda node 12.x
serverles 1.52.2
plugin 4.9.0

Syntax Error -------------------------------------------
 
 /builds/.../node_modules/serverless-plugin-warmup/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
  } catch {

**Comment by juanjoDiaz** [comment] 2020-04-08 14:23
That's a duplicate of #211.

You can read my answer there.
In short, you should update your development or CI environment (where you run the serverless commands) to node 10. Node 8 was EOL'd last December.

**Closed** 2020-04-16 06:51 UTC
Labels: duplicate
