### ISSUE TITLE
WarmUp-Plugin does not update old/exsting WarmUp-Lambdas

### ISSUE THREAD

**Issue by topfblumen** [FidelLimited/serverless-plugin-warmup#169] opened 2019-07-03 12:28 UTC
Existing or old Lambdas - Version 6x - won't be updated by the Plugin? Is this a feature or a bug ;)

**Comment by juanjoDiaz** [comment] 2019-07-03 12:37
Duplicate of #168 and #167 

Please ensure that you are using the latest version of the plugin.

**Comment by topfblumen** [comment] 2019-07-03 12:46
Does not work - i have to disable the plugin - deploy - and enable again

**Comment by topfblumen** [comment] 2019-07-03 13:21
> The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; id)

**Comment by juanjoDiaz** [comment] 2019-07-03 14:16
As mentioned in #167, node 8 is used in all versions after 4.0.0-rc.1  and node 10 is used since the last version 4.6.3-rc.1. I'd recommend using always the latest version.

In #168, it was mentioned that it seems that you have to disable the plugin, deploy, re-enable and redeploy. That indicates that issue is not in the plugin itself but in either the Serverless framework not generating the correct CloudFormation template or CloudFormation not doing the upgrade of the runtime correctly.

If you want to help, I'd really appreciate if you could troubleshoot this by:
- Checking your package.lock version (or even your node_modules) to see which version of this plugin is actually installed.
- Run `sls package` and check the generated CloudFormation template to see which runtime is assigned to the warmup function.

**Comment by juanjoDiaz** [comment] 2019-07-11 07:13
Any news on this?

**Comment by juanjoDiaz** [comment] 2019-07-15 06:49
Closing because of radio silence and since the solution is already posted above and in previous issues.

Feel free to reopen if needed. 🙂

**Closed by juanjoDiaz** 2019-07-15 06:49 UTC

**Comment by orsinijose** [comment] 2020-01-08 15:04
Howdy :)

I'm facing a similar issue. I managed to migrate my Lambda functions to Node.js 12.x, and the provider in Serverless config points to the right Node.js version. However, after I run `serverless package`, I see that the cloudformation template has set the runtime version of my warmup lambdas to Node.js 10.x

I disabled, reinstalled the plugin, re-enabled it, cleared npm cache, re-installed all libraries, and yet I'm dealing with the same issue.

```
$ node -v
v12.13.1

$ npm -v
6.13.4

$ sls --version
Framework Core: 1.60.5
Plugin: 3.2.7
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0

$ aws --version
aws-cli/1.16.46 Python/2.7.15 Darwin/18.7.0 botocore/1.12.36

```

Installed version of plugins/libraries:

```
"serverless-plugin-warmup": "^4.7.1-rc.1"
"aws-sdk": "^2.599.0"
```

Cloudformation template (after running `serverless package`):

```
      "warmUpPlugin": {
        "description": "Serverless WarmUp Plugin",
        "events": {
          "$ref": "$[\"service\"][\"custom\"][\"warmup\"][\"events\"]"
        },
        "handler": "_warmup/index.warmUp",
        "memorySize": 128,
        "name": "my-lambda-function-warmup",
        "runtime": "nodejs10.x",
        "package": {
          "artifact": ".serverless/my-lambda-function.zip"
        },
        "timeout": 10,
        "environment": {},
        "memory": 128,
        "vpc": {},
        "versionLogicalId": ...
      }
    }
```

Any guidance or help would be very appreciated. Thanks in advance!

**Comment by orsinijose** [comment] 2020-01-08 15:57
Whoops, I saw that on latest stable release, it defaults to Node.js 10.x
https://github.com/FidelLimited/serverless-plugin-warmup/blob/4.7.1-rc.1/src/index.js#L375
(I was looking at master). Anyways, the question would be: Is there any plan to release a new version of this plugin where 12.x is the default runtime of the warmup Lambda function? Thanks!

**Comment by juanjoDiaz** [comment] 2020-01-10 18:45
Sorry, @orsinijose, my season holiday got on the way. I'll cut a new release asp.
