### ISSUE TITLE
Why is the WarmUp plugin waiting for all lambdas to be invoked?

### ISSUE THREAD

**Issue by topfblumen** [FidelLimited/serverless-plugin-warmup#186] opened 2019-10-18 07:17 UTC
Why is the WarmUp plugin waiting for all lambdas to be called? 

- Ok - maybe something went wrong.
- But if you have a lot of Lambdas your runtime will be extended

**Comment by juanjoDiaz** [comment] 2019-10-19 12:35
This is a duplicate of #151 
Can you read my thoughts on that issue and comment there if you think that there is really a need to invoke the lambdas asynchronously.

**Closed by juanjoDiaz** 2019-10-19 12:35 UTC
Labels: duplicate
