### ISSUE TITLE
Unable to specify warmup for specified stage

### ISSUE THREAD

**Issue by drexler** [FidelLimited/serverless-plugin-warmup#103] opened 2019-01-11 13:20 UTC
Serverless.yml

```
provider:
  stage: ${file(${opt:variables}):stage}
  name: aws

  #other configurations & functions 

custom:
  warmup:
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
  enabled:
    - production
```

The lambdas are deployed under different accounts - stages - and there's the need to restrict warming of them to one tier. Using the above configuration fails. It might be possibly related to #100.

**Comment by juanjoDiaz** [comment] 2019-01-11 13:33
This is partially a duplicated of #100. Please read the comment there.

The problem is caused by the lack of maintainer blocking the releases (#101) 

In short, until the next release, change `enabled` by `default` 🙂 
Also, the indentation is incorrect.
```yml
custom:
  warmup:
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
    default:
      - production
```

**Comment by drexler** [comment] 2019-01-11 13:38
@juanjoDiaz thanks.

**Comment by juanjoDiaz** [comment] 2019-01-11 13:38
I'll close this then! Feel free to reopen if there is something unsolved.

**Closed by juanjoDiaz** 2019-01-11 13:38 UTC

**Comment by drexler** [comment] 2019-01-11 14:15
@juanjoDiaz sorry for commenting on a closed issue. You comment resolved my issue. I think the README needs updating to reflect how to specify the stages which the custom section of the `serverless.yml`. I can issue a quick PR for that, if necessary.

**Comment by juanjoDiaz** [comment] 2019-01-11 18:13
Hi @drexler,

The readme is correct, the problem is that we haven't released yet so NPM is serving you an older version.
If you see the readme on NPM, you'll see that it looks a bit different than in GitHub and actually shows the `default` option.

As general advice, check always the NPM readme better than the GitHub one, since they might be out of sync (like in this case).

Does that make sense?

**Comment by juanjoDiaz** [comment] 2019-02-10 20:43
Just FYI, everything is released now.
