### ISSUE TITLE
Not able to use severless-plugin-typescript

### ISSUE THREAD

**Issue by vlad-traceme** [FidelLimited/serverless-plugin-warmup#149] opened 2019-05-03 07:30 UTC
I see what warmup is not compatible with serverless-plugin-typescript. 

I am wondering if there will be any support for this soon.

**Comment by juanjoDiaz** [comment] 2019-05-03 12:08
This is a duplicate of #85. You can read there about the problem.

In short, there is nothing wrong with this plugin but with the typescript plugin which breaks any function that's not using TS.

There is also an issue in the `serverless-plugin-typescript` repository which has been unattended for 1.5 years (see my last comment in #85). So my expectations of them fixing this are very low.

I (and many others) moved to `serverless-webpack` a long time ago and I'd suggest that you do the same 🙂

**Closed by juanjoDiaz** 2019-05-03 12:08 UTC
Labels: duplicate
