### ISSUE TITLE
Incompatibility with serverless-plugin-typescript

### ISSUE THREAD

**Issue by dsmileym4** [FidelLimited/serverless-plugin-warmup#85] opened 2018-12-12 00:28 UTC
Every time I try and package I get:
```
{ file: undefined,
  start: undefined,
  length: undefined,
  messageText: "File '_warmup/index.ts' not found.",
  category: 1,
  code: 6053,
  reportsUnnecessary: undefined }

  Type Error ---------------------------------------------

  Cannot read property 'getLineAndCharacterOfPosition' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'getLineAndCharacterOfPosition' of undefined
    at allDiagnostics.forEach.diagnostic (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/src/typescript.ts:72:47)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/src/typescript.ts:68:18)
    at Generator.next (<anonymous>)
    at /Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/typescript.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/typescript.js:3:12)
    at Object.run (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/typescript.js:62:12)
    at TypeScriptPlugin.<anonymous> (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/src/index.ts:132:42)
    at Generator.next (<anonymous>)
    at /Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/index.js:3:12)
    at TypeScriptPlugin.compileTs (/Users/dsmiley/workspace/mfour-survey-service/node_modules/serverless-plugin-typescript/dist/src/index.js:103:16)
    at BbPromise.reduce (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/dsmiley/nvm/versions/node/v11.4.0/lib/node_modules/serverless/bin/serverless:44:28)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.4.0
     Serverless Version:     1.34.1
```
I've spent a day and half combing through your issues and going through step by step guide with no joy. Any help is greatly appreciated:

**Comment by juanjoDiaz** [comment] 2018-12-22 11:37
Any progress on this?
Can the issue be closed?

**Comment by robotlemons** [comment] 2018-12-27 19:30
@juanjoDiaz I am experiencing the same issue and put yml plugins in order you specified but does not work.

**Comment by aequasi** [comment] 2018-12-28 17:58
Same here. Order of plugins does not seem to help

**Comment by burkel24** [comment] 2019-02-01 17:22
I am able to use serverless-plugin-typescript without issue:

Here is my tsconfig:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "target": "es5",
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2015"],
    "rootDir": "./",
    "paths": {
      "*": ["*", "src/*"]
    }
  }
}
```

Here is the relevant portion of my `serverless.yml`:
```
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-sentry
  - serverless-plugin-warmup
```

**Comment by dsmileym4** [comment] 2019-02-01 17:59
Thank you for suggested fixes. I haven't had a chance to revisit this in our code. We implemented a work around which has to be removed to test this. If anyone else can verify this fix works please close this issue. It will be a while before we have any resources to verify.

**Comment by juanjoDiaz** [comment] 2019-02-10 16:27
I'll close this for now.

It seems clear that the problem is in serverless-plugin-typescript (which seems to be abandoned, so serverless-webpack might be a better option) and there seems to be a workaround.

Feel free to reopen if there is anything else.

**Closed by juanjoDiaz** 2019-02-10 16:27 UTC
Labels: invalid, question

**Comment by claridgicus** [comment] 2019-04-24 08:08
@juanjoDiaz sorry to drag this up - Serverless-Plugin-Typescript is under active dev at the moment, can we reopen this?

**Comment by juanjoDiaz** [comment] 2019-04-24 10:00
Is there anything that we can do here, @claridgicus? 

The problem, as stated in https://github.com/prisma/serverless-plugin-typescript/pull/79, is in the typescript plugin, so they just have to fix it. There isn't much that we can do...

Personally, I switched to https://www.npmjs.com/package/serverless-webpack long time ago.  🙂

**Comment by dsmileym4** [comment] 2019-04-25 22:39
I have circled back around to this and verified using serverless-webpack is the way to go. Solved my issues.

**Comment by piaverous** [comment] 2019-08-09 21:10
I have run into this issue in a full typescript setup. https://github.com/prisma/serverless-plugin-typescript/pull/79 was not enough to fix the issue for me, as I have (and need to keep) `allowJs: false` in my `tsconfig.json`.

`serverless package` would then error the following way
```
{ file: undefined,
  start: undefined,
  length: undefined,
  messageText: 'File \'_warmup/index.js\' has unsupported extension. The only supported extensions are \'.ts\', \'.tsx\', \'.d.ts\'.',
  category: 1,
  code: 6054,
  reportsUnnecessary: undefined }
```

It would be too costly for me to migrate to `serverless-webpack`, so I opened this PR to allow for generating the handler function in Typescript directly instead of JS: 
https://github.com/FidelLimited/serverless-plugin-warmup/pull/176

It works for me, but was wondering if there was a reason for _not_ doing this?

**Comment by JonRC** [comment] 2024-06-04 17:23
I just solved this problem for my case.  

`serverless-plugin-typescript` for `tsconfig.json` considers the folder above `node_modules` as the root. So if you are in a monorepo, use a custom path for the `tsconfig.json` file like the example.

```yml
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './path/for/service/tsconfig.json'
```
